apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container
  labels:
    app: multi-container
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multi-container
  template:
    metadata:
      labels:
        app: multi-container
    spec:
      containers:
      - name: server-1
        image: ryanwholey/fail-server:latest
        env:
        - name: PORT 
          value: "3000"
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /alive
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      - name: server-2
        image: ryanwholey/fail-server:latest
        env:
        - name: PORT 
          value: "8080"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /alive
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
